title: Sinan Oral
url: "https://sinan-oral.github.io"
baseurl: "/sinano"

markdown: kramdown

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Theme`s credit"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/sinano/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
